language: ruby
rvm:
  - 2.1.4
bundler_args: "--without production"
before_install:
  - gem update bundler
  - bundle config build.nokogiri --use-system-libraries
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database panlexicon_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
script:
  - bundle exec rake
after_script:
  - git checkout config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: pnpdy3VOB7hvtitD39L2HLD0Sa+3PfCBWC2dZ5gGPCpPPZTTMRBEx1cwbw4/R8LDnSLyO8xvsSMmJeh1UoYgvXJWnmkgpVQ4b0YY5PoSU9O4aApzXEU8GTh+oXTsjVLO/hBfHqcjADlgrH6ZjWMR9voytUvuR8wXFTI3lKoBH2g=
  app:
    master: panlexicon
  run:
    - "rake db:migrate"
