defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: panlexicon_development
  host: localhost
  <<: *defaults

test:
  database: panlexicon_test
  host: localhost
  min_messages: WARNING
  <<: *defaults

staging:
  database: panlexicon_staging
  <<: *defaults

production:
  database: panlexicon_production
  <<: *defaults
